export const projects = [
  {
    title: 'Unichat',
    description: "In this project I learned how to build a full Realtime Chat Application.  Made use of various sign-in / authorizations method such as google and facebook.  application includes features such as online statues, read receipts, and image support.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://unichatpractice.netlify.app/',
    visit: 'https://github.com/chillbroskie/unichat',
    id: 0,
  },
  {
    title: 'BroSearch',
    description: "Ability to search for up-to-date results, news, images, and videos. Includes a modern UI with dark mode all made with Tailwind CSS.  Responsive Google Clone used to practice more modern React.js. The Clone uses the Google Search API from rapidAPI.",
      image: '/images/5.jpg',
      tags: ['React', 'Tailwind', 'RapidAPI'],
    source: 'https://brosearch.netlify.app/',
    visit: 'https://github.com/chillbroskie/brosearch',
    id: 1,
  },
  {
    title: 'Instagram Clone',
    description: "Ability to search for up-to-date results, news, images, and videos. Includes a modern UI with dark mode all made with Tailwind CSS.  Responsive Google Clone used to practice more modern React.js. The Clone uses the Google Search API from rapidAPI.",
      image: '/images/5.jpg',
      tags: ['React', 'Tailwind', 'RapidAPI'],
    source: 'https://brosearch.netlify.app/',
    visit: 'https://github.com/chillbroskie/brosearch',
    id: 2,
  },
  {
    title: 'Discord NavBar',
    description: "Discord Navbar recreation to practice tailwind styling for the onHover effects and tooltips and using custom themes to change the color scheme of the base color attribute.",
      image: '/images/5.jpg',
      tags: ['React', 'Tailwind'],
    source: 'https://tailwindcss-discord-navbar.netlify.app/',
    visit: 'https://github.com/chillbroskie/tailwind-discord-practice',
    id: 3,
  },
  {
    title: 'CSS carousel animation',
    description: "practice creating a simple and pleasant fading animation for a carousel only using CSS",
      image: '/images/5.jpg',
      tags: ['JavaScript', 'CSS'],
    source: 'https://tailwindcss-discord-navbar.netlify.app/',
    visit: 'https://github.com/chillbroskie/tailwind-discord-practice',
    id: 3,
  },
  {
    title: 'React calculator',
    description: "React calculator made with the reducer hook",
      image: '/images/5.jpg',
      tags: ['React', 'Hooks'],
    source: 'https://react-calc-practice.netlify.app/',
    visit: 'https://github.com/chillbroskie/react-calc',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey in Westmoreland County Community College', },
  { year: 2018, text: 'Found an interest in Programming', },
  { year: 2019, text: 'Picked up additional CS classes at CalU', },
  { year: 2020, text: 'Started Nucamp and Codecademy', },
  { year: 2021, text: 'Graduated with Honors in Front-end', },
];